version: '3.8'

services:
  spring-boot:
    build: 
      context: ./springboot
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - "8080:8080"
    restart: always
    tty: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db
    networks:
      - app-network

  postgresql:
    image: postgres:15
    ports:
      - "5432:5432" 
    container_name: postgresql
    restart: always
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:  

networks:
  app-network:
    name: app-network
    driver: bridge